#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the FlashInfer project
"""Monokernel shape code generator.

Single source of truth: ``csrc/fused_moe/monomoe/shapes.json``.  The kernel is
template-specialized on (N, K, E) at compile time, so every distinct shape needs
its own ``Dims`` instantiation.  This script emits the C++ ``Dims_*`` structs the
hand-written binding/wrapper instantiate.

Outputs (written under ``csrc/fused_moe/monomoe/generated/``):

  dims_generated.inc     — Dims_BS{8,16}_E{E}_N{N}_K{K}_BlockFP8_WGMMA_TMA
                           structs, ``#include``d by src/moe_interface.h.
  configs_generated.inc  — per-shape ``MONO_CONFIGS_<KEY>(X)`` X-macro config
                           tables (+ ``MONO_CONFIGS_BS16_<KEY>`` where the shape
                           opts into BS16) and the active-shape ``#if`` ladder
                           (``MONO_ACTIVE_*``).  ``#include``d by
                           monomoe_binding.cu, which drives its generic
                           config_id dispatch off the ``MONO_ACTIVE_*`` macros.

Naming: shape-keyed ``E{E}_N{N}_K{K}`` is canonical and carries no model name;
the emitted structs are ``Dims_BS{8,16}_E{E}_N{N}_K{K}_BlockFP8_WGMMA_TMA``.

Usage:
  gen_shapes.py                    # regenerate all outputs
  gen_shapes.py --check            # exit 1 if any output is stale (CI guard)
  gen_shapes.py --print dims       # print the dims section to stdout (debug)
  gen_shapes.py --print configs    # print the configs section to stdout (debug)
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))  # repo root
MONO = os.path.normpath(os.path.join(HERE, ".."))  # monomoe/
SHAPES_JSON = os.path.join(MONO, "shapes.json")
GEN_DIR = os.path.join(MONO, "generated")  # C++ .inc files (#included by sources)
ATOM = 128

GEN_HEADER = (
    "// @generated by csrc/fused_moe/monomoe/tools/gen_shapes.py from\n"
    "// csrc/fused_moe/monomoe/shapes.json — DO NOT EDIT BY HAND.\n"
    "// Re-run gen_shapes.py after editing shapes.json.\n\n"
)


def cpp_name(shape):
    """Canonical shape-keyed C++ Dims infix: E{E}_N{N}_K{K}."""
    return f"E{shape['E']}_N{shape['N']}_K{shape['K']}"


def uch_of(shape, dct, cfg=None):
    """UP_COL_HALVES for a shape/config.

    DECOUPLED shapes pin an explicit `up_col_halves` (the up/down grids are
    chosen independently, so UCH does not follow the DCT coupling identity);
    return it verbatim.  Individual configs may also set `uch` to test a
    decoupled/raw carve without making the whole shape raw.  Otherwise,
    COUPLED shapes derive UCH = max(1, 2*N*DCT/(128*K)), mirroring the C++
    `up_col_halves<Dims>` fallback.  `dct` is per-config so a coupled shape
    with mixed DCT reports the right UCH per config."""
    if cfg is not None and cfg.get("uch") is not None:
        return int(cfg["uch"])
    if shape.get("up_col_halves") is not None:
        return int(shape["up_col_halves"])
    v = (2 * shape["N"] * dct) // (ATOM * shape["K"])
    return v if v > 0 else 1


def load_shapes():
    with open(SHAPES_JSON) as f:
        data = json.load(f)
    shapes = [s for s in data["shapes"] if "key" in s]
    # Validate constraints early — a bad shape should fail here, not at nvcc.
    seen_keys, seen_enk = set(), set()
    for s in shapes:
        E, N, K = s["E"], s["N"], s["K"]
        assert E % 32 == 0, f"{s['key']}: E={E} must be a multiple of 32"
        assert N % ATOM == 0, f"{s['key']}: N={N} must be a multiple of 128"
        assert K % ATOM == 0, f"{s['key']}: K={K} must be a multiple of 128"
        assert s["default_top_k"] <= 8, f"{s['key']}: default_top_k must be <= 8"
        assert s["configs"], f"{s['key']}: needs at least config 0"
        assert s["configs"][0]["id"] == 0, f"{s['key']}: config 0 must be the default"
        ids = [c["id"] for c in s["configs"]]
        assert ids == sorted(set(ids)), f"{s['key']}: config ids must be unique/sorted"
        assert s["key"] not in seen_keys, f"duplicate shape key {s['key']}"
        seen_keys.add(s["key"])
        enk = (E, N, K)
        assert enk not in seen_enk, f"duplicate (E,N,K)={enk}"
        seen_enk.add(enk)
    return shapes


def _emit_dims_struct(out, struct, s, c0, uch, bs):
    """Append one Dims_BS{bs}_<nm>_BlockFP8_WGMMA_TMA struct to `out`."""
    out.append(f"struct {struct} {{")
    out.append(f"  static constexpr uint32_t HIDDEN_STATES = {s['K']};")
    out.append(f"  static constexpr uint32_t K = {s['K']};")
    out.append(f"  static constexpr uint32_t N = {s['N']};")
    out.append(f"  static constexpr uint32_t BS = {bs};")
    out.append(f"  static constexpr uint32_t M = {bs};")
    out.append(f"  static constexpr uint32_t NUM_EXPERTS = {s['E']};")
    out.append(
        "  static constexpr QuantGranularity QUANT_GRAN = QuantGranularity::BLOCK_WISE;"
    )
    out.append("  static constexpr uint32_t BLOCK_SCALE_ROW = 128;")
    out.append("  static constexpr uint32_t BLOCK_SCALE_COL = 128;")
    out.append(
        "  static constexpr uint32_t UP_SCALE_ROWS =\n"
        "      (2 * N + BLOCK_SCALE_ROW - 1) / BLOCK_SCALE_ROW;"
    )
    out.append(
        "  static constexpr uint32_t UP_SCALE_COLS =\n"
        "      (K + BLOCK_SCALE_COL - 1) / BLOCK_SCALE_COL;"
    )
    out.append(
        "  static constexpr uint32_t DOWN_SCALE_ROWS =\n"
        "      (K + BLOCK_SCALE_ROW - 1) / BLOCK_SCALE_ROW;"
    )
    out.append(
        "  static constexpr uint32_t DOWN_SCALE_COLS =\n"
        "      (N + BLOCK_SCALE_COL - 1) / BLOCK_SCALE_COL;"
    )
    out.append("  struct KernelConfig {")
    out.append(f"    static constexpr std::uint32_t GRID_SIZE = {c0['grid']};")
    out.append("    static constexpr std::uint32_t BLOCK_SIZE = 384;")
    out.append("    static constexpr bool USE_WGMMA = true;")
    out.append("    static constexpr bool USE_TMA = true;")
    out.append(f"    static constexpr std::uint32_t K_STEP_DOWN = {c0['kdn']};")
    out.append(f"    static constexpr std::uint32_t K_STEP_UP = {c0['kup']};")
    # DOWN_COL_TILE: the kernel derives a per-shape default, but the raw
    # (UCH>=2) path needs the explicit tile.  For UCH==1 shapes we omit it so
    # the kernel default applies (byte-identical to the pre-knob behavior).
    if uch >= 2:
        out.append(f"    static constexpr std::uint32_t DOWN_COL_TILE = {c0['dct']};")
    # UP_COL_HALVES: pinned ONLY for decoupled shapes (explicit
    # `up_col_halves` in shapes.json).  Coupled shapes leave it absent so the
    # kernel derives it from DOWN_COL_TILE.  When present it decouples the
    # up-grid carve from DCT, which is what lets UP_GROUPS != DOWN_GROUPS.
    if s.get("up_col_halves") is not None:
        out.append(
            f"    static constexpr std::uint32_t UP_COL_HALVES = "
            f"{int(s['up_col_halves'])};"
        )
    # SLOTS: omit when it equals the shape's natural default (4 for UCH==1, 2
    # for UCH>=2) so we reproduce the up_w_slots<Dims> C++ fallback.  DECOUPLED
    # shapes MUST always emit it: the fallback derives depth from the DCT
    # coupling identity (which floors to 0 for a decoupled shape and would
    # wrongly return 4), so emitting it verbatim keeps base == config-0.
    natural_slots = 4 if uch == 1 else 2
    if c0["slots"] != natural_slots or s.get("up_col_halves") is not None:
        out.append(f"    static constexpr std::uint32_t UP_W_SLOTS = {c0['slots']};")
    out.append("    static constexpr bool USE_PAIR_LAYOUT = true;")
    out.append("  };")
    out.append("};")


def emit_dims(shapes):
    """Dims_* structs.  The base struct's KernelConfig knobs come from the
    shape's config[0] (the shipped default), so the base Dims and the config-0
    tunable instantiation are byte-identical — preserving the zero-regression
    contract.  UP_COL_HALVES is derived (not stored); DOWN_COL_TILE is emitted
    only when the raw (UCH>=2) path needs it."""
    out = [GEN_HEADER]
    for s in shapes:
        nm = cpp_name(s)
        c0 = s["configs"][0]
        uch = uch_of(s, c0["dct"], c0)
        struct = f"Dims_BS8_{nm}_BlockFP8_WGMMA_TMA"
        out.append(
            f"// E={s['E']} N={s['N']} K={s['K']} block-wise FP8  "
            f"(default cfg0: grid={c0['grid']} DCT={c0['dct']} "
            f"KUP={c0['kup']} KDN={c0['kdn']} SLOTS={c0['slots']} "
            f"=> UP_COL_HALVES={uch})"
        )
        _emit_dims_struct(out, struct, s, c0, uch, bs=8)
        # BS16 companion tag: identical KernelConfig knobs (config-0), BS and M
        # doubled to 16.  The kernel template body is shared with BS8
        # (moe_kernel_topk_impl); host dispatch selects the BS16 op for
        # 8 < token_count <= 16.  Opt-in per shape via `"bs16": true`.
        if s.get("bs16"):
            struct16 = f"Dims_BS16_{nm}_BlockFP8_WGMMA_TMA"
            out.append(
                f"// BS16 companion of {struct} — selected for token_count in (8, 16]."
            )
            _emit_dims_struct(out, struct16, s, c0, uch, bs=16)
        out.append("")
    return "\n".join(out)


def bs16_config_ids(s):
    """Config ids to instantiate for the BS16 dispatcher.

    Defaults to all configs for a bs16-enabled shape, but a shape may restrict
    this (``bs16_config_ids``) when some BS8 candidates exceed the larger BS16
    shared-memory layout.  Empty for shapes that do not opt into BS16."""
    if not s.get("bs16"):
        return []
    if s.get("bs16_config_ids") is not None:
        return list(s["bs16_config_ids"])
    return [c["id"] for c in s["configs"]]


def _config_uch_arg(c):
    """Explicit UCH template arg for DimsTunable; 0 => derive/preserve."""
    return int(c.get("uch", 0) or 0)


def _config_dpd_arg(c):
    """Explicit DOWN_PIPE_DEPTH template arg for DimsTunable; 0 => classic
    2-slot double buffer (byte-identical to the pre-knob layout)."""
    return int(c.get("dpd", 0) or 0)


def _config_x_line(c):
    """One X-macro row: X(id, GRID, DCT, KUP, KDN, SLOTS, UCH, DPD).

    Column order matches DimsTunable<Base, GRID, DCT, KUP, KDN, SLOTS, UCH,
    DPD> in src/moe_interface.h exactly."""
    note = f"  /* {c['note']} */" if c.get("note") else ""
    return (
        f"  X({c['id']}, {c['grid']}, {c['dct']}, {c['kup']}, "
        f"{c['kdn']}, {c['slots']}, {_config_uch_arg(c)}, "
        f"{_config_dpd_arg(c)}){note}"
    )


def emit_configs(shapes):
    """Per-shape ``MONO_CONFIGS_<KEY>(X)`` X-macro config tables plus the
    active-shape ``#if`` ladder the binding uses to pick ONE shape per module.

    The binding drives its generic config_id dispatch off these macros: it
    expands ``MONO_CONFIGS_<active>`` (and, at BS16 token counts,
    ``MONO_CONFIGS_BS16_<active>``) into ``DimsTunable`` instantiations and a
    ``switch(config_id)``.  Only the shape whose ``MONOMOE_SHAPE_*`` define is
    set (by the JIT layer) is compiled — the include itself expands nothing."""
    out = [GEN_HEADER]
    out.append("// clang-format off")
    out.append("")
    for s in shapes:
        nm = cpp_name(s)
        c0 = s["configs"][0]
        uch0 = uch_of(s, c0["dct"], c0)
        out.append(
            f"// E={s['E']} N={s['N']} K={s['K']} — {len(s['configs'])} config(s); "
            f"cfg0 default (UP_COL_HALVES={uch0})."
        )
        out.append(f"#define MONO_CONFIGS_{nm}(X) \\")
        out.append(" \\\n".join(_config_x_line(c) for c in s["configs"]))
        out.append("")
        ids16 = set(bs16_config_ids(s))
        if ids16:
            out.append(
                "// BS16 companion configs (subset that fits the BS16 SHM budget)."
            )
            out.append(f"#define MONO_CONFIGS_BS16_{nm}(X) \\")
            out.append(
                " \\\n".join(
                    _config_x_line(c) for c in s["configs"] if c["id"] in ids16
                )
            )
        else:
            # No BS16 for this shape: expand to nothing so the binding's
            # unconditional MONO_CONFIGS_BS16_<active>(X) use is well-formed.
            out.append("// (no BS16 companion for this shape)")
            out.append(f"#define MONO_CONFIGS_BS16_{nm}(X)")
        out.append("")

    # Active-shape selector.  The JIT layer passes exactly one
    # -DMONOMOE_SHAPE_E{E}_N{N}_K{K}; this ladder binds the generic
    # MONO_ACTIVE_* names the binding consumes to that shape's Base type, its
    # config table, and whether it has a BS16 companion.
    out.append(
        "// ── Active-shape selector (exactly one MONOMOE_SHAPE_* is -D'd) ──────"
    )
    first = True
    for s in shapes:
        nm = cpp_name(s)
        guard = "#if" if first else "#elif"
        first = False
        has_bs16 = 1 if bs16_config_ids(s) else 0
        out.append(f"{guard} defined(MONOMOE_SHAPE_{nm})")
        out.append(f"#define MONO_ACTIVE_KEY {nm}")
        out.append(
            f"#define MONO_ACTIVE_BASE ::monomoe::Dims_BS8_{nm}_BlockFP8_WGMMA_TMA"
        )
        out.append(
            f"#define MONO_ACTIVE_BASE_BS16 ::monomoe::Dims_BS16_{nm}_BlockFP8_WGMMA_TMA"
        )
        out.append(f"#define MONO_ACTIVE_CONFIGS(X) MONO_CONFIGS_{nm}(X)")
        out.append(f"#define MONO_ACTIVE_CONFIGS_BS16(X) MONO_CONFIGS_BS16_{nm}(X)")
        out.append(f"#define MONO_ACTIVE_HAS_BS16 {has_bs16}")
    out.append("#else")
    out.append(
        '#error "monomoe: no MONOMOE_SHAPE_* define set; '
        'the JIT layer must pass exactly one -DMONOMOE_SHAPE_E{E}_N{N}_K{K}."'
    )
    out.append("#endif")
    out.append("")
    out.append("// clang-format on")
    out.append("")
    return "\n".join(out)


# ── driver ──────────────────────────────────────────────────────────────────

OUTPUTS = {
    "dims_generated.inc": emit_dims,
    "configs_generated.inc": emit_configs,
}


def render(shapes):
    return {fn: emitter(shapes) for fn, emitter in OUTPUTS.items()}


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if any generated file is stale (CI guard)",
    )
    ap.add_argument(
        "--print",
        dest="section",
        choices=["dims", "configs"],
        help="print one section to stdout and exit (no files written)",
    )
    args = ap.parse_args()

    shapes = load_shapes()

    if args.section:
        print(render(shapes)[f"{args.section}_generated.inc"])
        return

    os.makedirs(GEN_DIR, exist_ok=True)
    rendered = render(shapes)
    stale = []
    for fn, content in rendered.items():
        path = os.path.join(GEN_DIR, fn)
        old = None
        if os.path.exists(path):
            with open(path) as f:
                old = f.read()
        if old != content:
            stale.append(fn)
            if not args.check:
                with open(path, "w") as f:
                    f.write(content)
    if args.check:
        if stale:
            print(
                f"STALE generated files (re-run gen_shapes.py): {stale}",
                file=sys.stderr,
            )
            sys.exit(1)
        print("generated files up to date")
    else:
        for fn in rendered:
            print(f"  {os.path.relpath(os.path.join(GEN_DIR, fn), ROOT)}")
        print(f"wrote {len(rendered)} files ({len(stale)} changed: {stale or 'none'})")
        print(f"shapes: {[s['key'] for s in shapes]}")


if __name__ == "__main__":
    main()
